### ISSUE TITLE
Create Class Skeleton and Documentation for GameModerator

### ISSUE THREAD

**Issue by cesiu** [cpe305/fall2016-project-cesiu#1]
Based on the class diagram found in the diagrams directory, create a skeleton of the GameModerator class. Just include the public methods, for now, with dummy return values if necessary. You'll need to define the inner GameRound class and GameThrow enumeration to get it to compile. This should result in one file within the src/main/java directory: GameModerator.java.

Add a JavaDoc comment at the beginning of the file and include yourself as an author. If you have time, methods and their parameters and return values should also be JavaDoc'd.

Create a new branch (use your username as the branch name), push your file to it, and make a pull request.

**Comment by sarahpadlipsky** [comment]
Fixed with 3b7c5cc.

Branch name is GameModerator instead of my username (sorry).
