### ISSUE TITLE
Unit Tests for RandomAI

### ISSUE THREAD

**Issue by cesiu** [cpe305/fall2016-project-cesiu#3]
Write unit tests for the RandomAI class found in src/main/java/RandomAI.java. Both methods and both constructors should be tested; additionally, a unit test should verify that RandomAI implements GameAI. 

Unit tests should be written for JUnit 4 and placed in the src/test/java directory. Please follow the format of `<assert>(<description>, <expected>, <actual>)`.

The EclEmma plugin for Eclipse can verify that tests have 100% branch coverage of a class.

Push completed tests to a branch titled with your username and make a pull request.

**Comment by cbrown83** [comment]
Created test skeleton. Will continue work around 6pm. Will finish and push by tonight :)

**Comment by cbrown83** [comment]
Tests done. Full coverage per EclEmma. Trying to push to git...

**Comment by cesiu** [comment]
Completed by 56fb60a.
